mongodb:
  image: mongo
  container_name: ngsi_mongo
  volumes:
    - ./data:/data/db

encrypt:
  build: .
  container_name: ngsi_nodejs
  ports:
    - "8000:8000"
  links:
    - mongodb:mongodb
  command: npm start
